// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

import "./ERC4907.sol";
import "./IAnyNFTCollection.sol";
import "../node_modules/@openzeppelin/contracts/utils/Counters.sol";
import "../node_modules/@openzeppelin/contracts/access/Ownable.sol";
import "./Utils.sol";

/*
si jamais ca peut en aider certains :
npm install @ganache/console.log --save-exact
avec un petit import dans le smart contract le temps de debugger
import "../node_modules/@ganache/console.log/console.sol";
*/
contract AnyNFTCollection is ERC4907, IAnyNFTCollection, Ownable{

    using Counters for Counters.Counter;



    Counters.Counter private tokenIds;

    // Renter address allowed to mint NFTs
    address public renter;

    // NFTs in collection generated by the renter and max
    Utils.Tool[]  tools;
    uint256 public constant MAX_TOOLS = 100;

    constructor(string memory _name, string memory _symbol, address _owner) ERC4907(_name,_symbol){
        renter = _owner;

        // Fill the first element of tools to match NFT tokenId
        Utils.Tool memory _tool0;
        tools.push(_tool0);
    }



/* ***********************************************
*   Events 
*********************************************** */



/* ***********************************************
*   Modifiers 
*********************************************** */
    /**
    * @dev Only renter can call
    */
    modifier onlyRenter(address _from) {
        require(renter == _from, "You are not the renter of that collection.");
        _;
    }
 
/* ***********************************************
*   Getters 
*********************************************** */
    function getTools() public view returns (Utils.Tool[] memory){
        return tools;
    }

    function getToolsByTokenID(uint _tokenId) public view returns (Utils.Tool memory){
        require(tokenIds.current() >= _tokenId, "Tool does not exist");
        return tools[_tokenId];
    }

/* ***********************************************
*    mint / burn / rent / giveBack
*********************************************** */
   
    /**
    * @notice mint a tool NFT and add it to the array
    * @dev
    * Requirements: tokenURI, title and description can't be empty.
    * @return tokenIdof the token
    */
   function mint(string calldata _tokenURI, uint _serialId, string memory _title, string memory _description, address _from) external onlyRenter(_from)  returns (uint256) {
        require(tools.length < MAX_TOOLS, "Maximum number of tools reached");
        require(!Utils.isEqualString(_tokenURI,""), "token URI can't be empty");
        require(!Utils.isEqualString(_title,""), "title can't be empty");
        require(!Utils.isEqualString(_description,""), "description can't be empty");

        tokenIds.increment();

        tools.push(Utils.Tool(_serialId, _title, _description, true));

        uint newToolId = tokenIds.current();
        _mint(renter, newToolId);
        _setTokenURI(newToolId, _tokenURI);

        return newToolId;
    }


   /* 
    function burn(uint256 _tokenId) external onlyRenter {
        _burn(_tokenId);
        for
    }*/


function rentTool(uint _toolId, address _to) external {
        require(tokenIds.current() >= _toolId, "Tool does not exist");
        require(tools[_toolId].isAvailable, "Tool is not available");

/*
        // Enregistrement des informations de location dans le mapping _users de ERC4907
        _users[tools[_toolId].owner].expires = end;
        _users[msg.sender].user = address(this);
        _users[msg.sender].expires = end;

        // Changement du propriétaire de l'outil
        _tools[toolId].owner = msg.sender;
        _tools[toolId].isAvailable = false;

       // emit RentTool(toolId, dayPrice, caution, start, end, msg.sender);*/
    }
    


/* ***********************************************
*    extendRental / dispute 
*********************************************** */


}


   
 