name: GitHub Actions CI
run-name: ${{ github.actor }} Go for CI 🚀
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  github_actions_test_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  # lint du code

  run_test_job:
    runs-on: ubuntu-latest
    name: Run solidity tests !
    services:
      ganache:
        image: trufflesuite/ganache-cli:v6.12.1
        ports:
          - 8545:8545
          - 8546:8546
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install & setup Node.js
        working-directory: truffle
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies (node & truffle)
        working-directory: ./truffle
        run: |
          npm install
          npm install -g truffle

      - name: Compile Contracts
        working-directory: ./truffle
        run: truffle compile

      - name: Migrate Contracts
        working-directory: ./truffle
        run: truffle migrate --reset

      - name: Run Truffle tests
        working-directory: ./truffle
        run: truffle test

  # code coverage du code
